### ISSUE TITLE
What's the version of timm?

### ISSUE THREAD

**Issue by yaolu-zjut** [GeorgeCazenavette/glad#8]
Hi, I am running with your code, but get this error.
Traceback (most recent call last):
  File "/public/ly/glad-main/glad-main/distill_dm.py", line 219, in <module>
    main(args)
  File "/public/ly/glad-main/glad-main/distill_dm.py", line 62, in main
    G, zdim, w_dim, num_ws = load_sgxl(args.res, args)
  File "/public/ly/glad-main/glad-main/glad_utils.py", line 284, in load_sgxl
    G = legacy.load_network_pkl(f)[key]
  File "/public/ly/glad-main/glad-main/stylegan_xl/legacy.py", line 25, in load_network_pkl
    data = _LegacyUnpickler(f).load()
  File "/public/ly/glad-main/glad-main/stylegan_xl/legacy.py", line 77, in find_class
    return super().find_class(module, name)
ModuleNotFoundError: No module named 'timm.models.layers.conv2d_same'

I try the timm==0.9.2 and 0.9.16, but it does not work. So maybe you can provide the actual version of timm. Thanks.

**Comment by karthiknm** [comment]
Try using 0.4.12. That works.

**Comment by GeorgeCazenavette** [comment]
Hello!

So sorry for the late reply.

I think it's `timm==0.4.12`, taken from the sdxl repo.
